version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ##    if you want to expose app as well.
    # ports:
    #   - 8080:8080
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/apps/api/node_modules
    networks:
      - node_network

  proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
    depends_on:
      - api
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node_network
  
networks:
  node_network: