version: '3.8'

services:
  api:
    build:
      image: api:latest
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
      - /usr/src/app/apps/api/node_modules/
    networks:
      - node_network
    ##    if you want to expose app as well.
    # ports:
    #   - 8080:8080

  proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
    depends_on:
      - api
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node_network
  
networks:
  node_network: